# Generated by Django 4.2.1 on 2023-05-31 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cedula', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('celular', models.BigIntegerField()),
            ],
            options={
                'db_table': 'cliente',
            },
        ),
        migrations.CreateModel(
            name='Repuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_nombre_repuesto', models.CharField(max_length=30, unique=True)),
                ('r_cantidad', models.IntegerField()),
                ('r_valor_proveedor', models.FloatField()),
                ('r_valor_publico', models.FloatField()),
            ],
            options={
                'db_table': 'repuesto',
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_descripcion', models.CharField(max_length=100)),
                ('s_mano_obra', models.FloatField()),
                ('s_fecha_entrada', models.DateTimeField()),
                ('s_fecha_salida', models.DateTimeField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cliente')),
            ],
            options={
                'db_table': 'servicio',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('cedula', models.BigIntegerField(primary_key=True, serialize=False)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('contrasena', models.CharField(max_length=128)),
                ('nombre', models.CharField(max_length=255)),
                ('celular', models.BigIntegerField()),
                ('rol', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('placa', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'vehiculo',
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('v_descripcion', models.CharField(max_length=100)),
                ('v_fecha', models.DateTimeField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cliente')),
            ],
            options={
                'db_table': 'venta',
            },
        ),
        migrations.CreateModel(
            name='Valoracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.IntegerField()),
                ('opinion', models.CharField(max_length=255)),
                ('servicio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.servicio')),
            ],
            options={
                'db_table': 'valoracion',
            },
        ),
        migrations.AddField(
            model_name='servicio',
            name='s_vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.vehiculo'),
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('v_cantidad', models.IntegerField()),
                ('repuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.repuesto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.venta')),
            ],
            options={
                'db_table': 'detalleVenta',
            },
        ),
        migrations.CreateModel(
            name='DetalleServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_cantidad', models.IntegerField()),
                ('repuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.repuesto')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.servicio')),
            ],
            options={
                'db_table': 'detalleServicio',
            },
        ),
    ]
