# Generated by Django 4.2.1 on 2023-05-17 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('contrasena', models.CharField(max_length=128)),
                ('nombre', models.CharField(max_length=255)),
                ('celular', models.BigIntegerField()),
                ('cedula', models.BigIntegerField()),
                ('rol', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
    ]
