# Generated by Django 4.2 on 2023-07-08 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_venta_v_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleventa',
            name='dv_valor_proveedor',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='dv_valor_publico',
            field=models.FloatField(default=0.0),
        ),
    ]
