# Generated by Django 4.2.1 on 2023-06-01 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_servicio_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='s_fecha_entrada',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='s_fecha_salida',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='venta',
            name='v_fecha',
            field=models.DateTimeField(editable=False),
        ),
    ]
