# Generated by Django 4.2.1 on 2023-06-01 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_servicio_s_fecha_entrada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='s_fecha_salida',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
