# Generated by Django 4.2 on 2023-07-08 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_detalleventa_dv_valor_proveedor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleservicio',
            name='ds_valor_proveedor',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='detalleservicio',
            name='ds_valor_publico',
            field=models.FloatField(default=0.0),
        ),
    ]
