# Generated by Django 4.2 on 2023-07-27 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_detalleservicio_ds_valor_proveedor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='estado_factura',
            field=models.BooleanField(default=False),
        ),
    ]
