# Generated by Django 4.2.1 on 2023-06-01 18:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_servicio_s_fecha_salida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='s_fecha_entrada',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
