# Generated by Django 4.2.1 on 2023-06-01 18:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_servicio_s_fecha_entrada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='v_fecha',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
