# Generated by Django 4.2.1 on 2023-06-01 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_venta_v_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='s_total',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='v_total',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
