# Generated by Django 4.2.1 on 2023-06-01 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_servicio_s_total_venta_v_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='s_mano_obra',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
