# Generated by Django 4.2.1 on 2023-06-01 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_servicio_s_mano_obra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='s_total',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='v_total',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
