# Generated by Django 4.2.1 on 2023-06-01 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_servicio_s_total_alter_venta_v_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleservicio',
            name='s_cantidad',
            field=models.FloatField(),
        ),
    ]
