# Generated by Django 4.2.1 on 2023-06-01 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_detalleservicio_s_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleservicio',
            name='s_cantidad',
            field=models.IntegerField(),
        ),
    ]
