# Generated by Django 4.2.1 on 2023-06-02 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_detalleservicio_s_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='s_total',
            field=models.FloatField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='venta',
            name='v_total',
            field=models.FloatField(default=0, editable=False),
        ),
    ]
