# Generated by Django 4.2.1 on 2023-06-02 21:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_servicio_s_total_alter_venta_v_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='valoracion',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
